spring:
  datasource:
    # 1. Đã cập nhật đúng host aws-1-ap-northeast-1 của bạn
    # 2. Giữ nguyên cổng 6543 và thêm sslmode=require ở cuối
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

    # Username đúng cấu trúc dựa trên chuỗi JDBC của bạn
    username: postgres.ksmnsefgguukmfzdadcd

    # Mật khẩu database của bạn (nhớ thay đổi nếu bạn có cập nhật mật khẩu mới)
    password: 'autowashcar123'

    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
management:
  health:
    redis:
      enabled: false
logging:
  level:
    com.autowash: DEBUG
    org.flywaydb: INFO

#  d6d0faa6-f06b-4935-99ab-78117de3f75a
cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}
